openapi: 3.1.0
info:
  title: Account API
  description: API for managing accounts and retrieving account information
  version: 1.0.0
  contact:
    name: Elastic Software Foundation
servers:
  - url: /v1
    description: Version 1 API
paths:
  /accounts:
    post:
      summary: Create a new account
      description: Creates a new user account with the provided information
      operationId: createAccount
      tags:
        - accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountInput'
      responses:
        '200':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountOutput'
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error
  /accounts/{accountId}:
    get:
      summary: Get account details
      description: Retrieves the details of a specific account by its ID
      operationId: getAccount
      tags:
        - accounts
      parameters:
        - name: accountId
          in: path
          required: true
          description: The unique identifier of the account
          schema:
            type: string
      responses:
        '200':
          description: Account details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountOutput'
        '404':
          description: Account not found
        '500':
          description: Internal server error
components:
  schemas:
    AccountInput:
      type: object
      properties:
        country:
          type: string
          description: The country code for the user's location
          example: "US"
        firstName:
          type: string
          description: The user's first name
          example: "John"
        lastName:
          type: string
          description: The user's last name
          example: "Doe"
        email:
          type: string
          format: email
          description: The user's email address
          example: "john.doe@example.com"
      required:
        - country
        - firstName
        - lastName
        - email
    AccountOutput:
      type: object
      properties:
        accountId:
          type: string
          description: The unique identifier of the account
          example: "123e4567-e89b-12d3-a456-426614174000"
        country:
          type: string
          description: The country code for the user's location
          example: "US"
        firstName:
          type: string
          description: The user's first name
          example: "John"
        lastName:
          type: string
          description: The user's last name
          example: "Doe"
        email:
          type: string
          format: email
          description: The user's email address
          example: "john.doe@example.com"
      required:
        - accountId
        - country
        - firstName
        - lastName
        - email