spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    consumer:
      enable-auto-commit: false
      isolation-level: read_committed
      max-poll-records: 500
      heartbeat-interval: 2000
      auto-offset-reset: latest
      properties:
        max.poll.interval.ms: "10000"
        session.timeout.ms: "30000"
        partition.assignment.strategy: "org.apache.kafka.clients.consumer.CooperativeStickyAssignor"
    producer:
      acks: all
      retries: 2147483647
      properties:
        linger.ms: "0"
        retry.backoff.ms: "0"
        enable.idempotence: "true"
        max.in.flight.requests.per.connection: "1"
