/*
 * Copyright 2022 - 2026 The Original Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *           http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */

package org.elasticsoftware.akces.agentic.agent;

import com.embabel.agent.api.annotation.AchievesGoal;
import com.embabel.agent.api.annotation.Action;
import com.embabel.agent.api.annotation.Condition;
import com.embabel.agent.api.annotation.EmbabelComponent;
import org.elasticsoftware.akces.agentic.events.MemoryRevokedEvent;
import org.elasticsoftware.akces.agentic.events.MemoryStoredEvent;
import org.elasticsoftware.akces.aggregate.AgenticAggregateMemory;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Central Embabel component that provides reusable Goals, Actions, and Conditions for
 * Akces-based agentic systems.
 *
 * <p>This class is annotated with {@link EmbabelComponent} and is automatically discovered
 * by the {@code AgentPlatform} via component scanning. It provides the foundational agent
 * capabilities for memory management and knowledge learning that all agentic aggregates
 * share.
 *
 * <h2>Actions</h2>
 * <ul>
 *   <li>{@link #storeMemory storeMemory} — Store a learned fact as a
 *       {@link MemoryStoredEvent}</li>
 *   <li>{@link #forgetMemory forgetMemory} — Revoke an outdated or incorrect memory as a
 *       {@link MemoryRevokedEvent}</li>
 *   <li>{@link #recallMemories recallMemories} — Search stored memories by subject or
 *       keyword (read-only)</li>
 * </ul>
 *
 * <h2>Conditions</h2>
 * <ul>
 *   <li>{@link #hasMemories hasMemories} — Evaluates whether any memories are present on
 *       the blackboard</li>
 * </ul>
 *
 * <h2>Goals</h2>
 * <ul>
 *   <li>{@link #learnFromProcess learnFromProcess} — Multi-step LLM reasoning goal that
 *       analyzes session context and distills useful memories</li>
 * </ul>
 *
 * @see MemoryStoredEvent
 * @see MemoryRevokedEvent
 * @see AgenticAggregateMemory
 * @see MemoryLearningResult
 */
@EmbabelComponent
public class AkcesAgentComponent {

    /**
     * Maximum number of new memories that may be stored in a single agent process
     * execution. This prevents memory bloat from a single interaction.
     */
    static final int MAX_NEW_MEMORIES_PER_EXECUTION = 3;

    // -------------------------------------------------------------------------
    // Actions
    // -------------------------------------------------------------------------

    /**
     * Stores a learned fact as a new memory entry for the agentic aggregate.
     *
     * <p>Reads the aggregate identifier from the blackboard and accepts the memory
     * content fields ({@code subject}, {@code fact}, {@code citations}, {@code reason})
     * as inputs — typically generated by the LLM during the learning process. The action
     * produces a {@link MemoryStoredEvent} directly (bypassing the internal command path)
     * which is collected by the partition and applied through the built-in
     * {@code @EventSourcingHandler} (calling {@code MemoryAwareState.withMemory()}).
     *
     * @param agenticAggregateId the unique identifier of the agentic aggregate instance,
     *                           read from the blackboard
     * @param subject            a short (1–3 word) topic label for the memory
     *                           (e.g. "error handling", "market patterns")
     * @param fact               a clear, concise factual statement (max ~200 characters)
     * @param citations          source reference — the command/event type that triggered
     *                           this learning, or relevant data points
     * @param reason             why this fact is worth remembering — what future decisions
     *                           it informs (2–3 sentences)
     * @return a {@link MemoryStoredEvent} containing all memory metadata
     */
    @Action(description = "Store a learned fact as a memory entry for the agentic aggregate")
    public MemoryStoredEvent storeMemory(
            String agenticAggregateId,
            String subject,
            String fact,
            String citations,
            String reason) {
        return new MemoryStoredEvent(
                agenticAggregateId,
                UUID.randomUUID().toString(),
                subject,
                fact,
                citations,
                reason,
                Instant.now());
    }

    /**
     * Revokes (forgets) a memory entry that is no longer relevant or accurate.
     *
     * <p>Takes the {@code memoryId} of the entry to revoke and a {@code reason} from the
     * blackboard, reads the aggregate identifier, and produces a
     * {@link MemoryRevokedEvent}. The event is applied through the built-in
     * {@code @EventSourcingHandler} (calling {@code MemoryAwareState.withoutMemory()}).
     *
     * <p>This action enables agent self-management of its knowledge base: the agent can
     * correct its knowledge by removing outdated or incorrect facts, and can enforce
     * memory capacity limits by evicting the oldest entries.
     *
     * @param agenticAggregateId the unique identifier of the agentic aggregate instance,
     *                           read from the blackboard
     * @param memoryId           the UUID of the memory entry to revoke
     * @param reason             the reason the memory is being revoked
     * @return a {@link MemoryRevokedEvent} for the identified memory entry
     */
    @Action(description = "Revoke a memory entry that is no longer relevant or accurate")
    public MemoryRevokedEvent forgetMemory(
            String agenticAggregateId,
            String memoryId,
            String reason) {
        return new MemoryRevokedEvent(
                agenticAggregateId,
                memoryId,
                reason,
                Instant.now());
    }

    /**
     * Searches stored memories by subject or keyword to retrieve relevant facts.
     *
     * <p>Reads the current {@code List<AgenticAggregateMemory>} from the blackboard and
     * filters entries based on the provided {@code query}. Matching is case-insensitive
     * and checks the memory's subject, fact content, and reason fields. If no query is
     * provided (null or blank), all memories are returned.
     *
     * <p>This action is declared {@code readOnly = true} since it has no side effects —
     * it only inspects the current memory list without modifying state.
     *
     * @param memories the current list of memories from the blackboard; may be
     *                 {@code null} or empty
     * @param query    a search term to filter memories by subject, fact, or reason;
     *                 if {@code null} or blank, all memories are returned
     * @return an unmodifiable list of matching memories; never {@code null}
     */
    @Action(description = "Search stored memories by subject or keyword to retrieve relevant facts",
            readOnly = true)
    public List<AgenticAggregateMemory> recallMemories(
            List<AgenticAggregateMemory> memories,
            String query) {
        if (memories == null || memories.isEmpty()) {
            return List.of();
        }
        if (query == null || query.isBlank()) {
            return List.copyOf(memories);
        }
        String lowerQuery = query.toLowerCase();
        return memories.stream()
                .filter(m -> matchesQuery(m, lowerQuery))
                .toList();
    }

    // -------------------------------------------------------------------------
    // Conditions
    // -------------------------------------------------------------------------

    /**
     * Evaluates whether the blackboard contains one or more
     * {@link AgenticAggregateMemory} objects.
     *
     * <p>This condition is used as a precondition for actions that depend on prior
     * knowledge. For example, "recall memories" is only meaningful when memories exist.
     *
     * @param memories the current list of memories from the blackboard; may be
     *                 {@code null} or empty
     * @return {@code true} if at least one memory is present; {@code false} otherwise
     */
    @Condition(name = "hasMemories")
    public boolean hasMemories(List<AgenticAggregateMemory> memories) {
        return memories != null && !memories.isEmpty();
    }

    // -------------------------------------------------------------------------
    // Goals
    // -------------------------------------------------------------------------

    /**
     * Goal action that completes the learning cycle by analyzing current session
     * information and distilling useful memories.
     *
     * <p>This method is annotated with both {@link AchievesGoal} and {@link Action}.
     * The {@code @AchievesGoal} annotation declares the "LearnFromProcess" goal in the
     * Embabel GOAP planner, and the planner orchestrates a multi-step reasoning pipeline
     * using the available actions:
     * <ol>
     *   <li>{@link #recallMemories recallMemories} — check existing memories to avoid
     *       duplicates and assess capacity</li>
     *   <li>(LLM reasoning over Blackboard session context) — determine what new facts
     *       were learned, respecting the max-3 limit</li>
     *   <li>{@link #storeMemory storeMemory} — persist new memories
     *       (producing {@link MemoryStoredEvent})</li>
     *   <li>{@link #forgetMemory forgetMemory} — evict oldest memories if capacity
     *       exceeded, or replace outdated ones (producing {@link MemoryRevokedEvent})</li>
     * </ol>
     *
     * <p><b>Constraints enforced by the LLM planner:</b>
     * <ul>
     *   <li>Maximum {@value #MAX_NEW_MEMORIES_PER_EXECUTION} new memories per agent
     *       process execution</li>
     *   <li>No duplicate memories — existing memories must be checked before storing</li>
     *   <li>Memory capacity enforcement — after storing, if total exceeds
     *       {@code maxMemories}, evict oldest via {@link #forgetMemory}</li>
     * </ul>
     *
     * @param memories the current list of memories from the blackboard
     * @return a {@link MemoryLearningResult} summarizing what was learned
     */
    @AchievesGoal(description = """
            Analyze current session information and distill useful memories.
            
            Constraints:
            - Maximum 3 new memories per agent process execution (prevents memory bloat)
            - No duplicate memories: check existing memories before storing and skip any \
            fact that is already stored (same subject + substantially similar fact content)
            - Memory capacity enforcement: after storing new memories, if total memory count \
            exceeds maxMemories, evict oldest entries using ForgetMemoryAction until within limit
            
            Memory field guidance:
            - subject: 1-3 word topic label (e.g. "error handling", "user preferences")
            - fact: clear, concise factual statement (max ~200 chars), actionable and self-contained
            - citations: source reference — the command/event type that triggered this learning
            - reason: why this fact is worth remembering, 2-3 sentences explaining significance
            
            Plan:
            1. RecallMemoriesAction to check existing memories (avoid duplicates, assess capacity)
            2. Determine what new facts were learned from the session context (max 3)
            3. StoreMemoryAction for each new memory
            4. ForgetMemoryAction for oldest memories if capacity exceeded""")
    @Action(description = """
            Complete the learning process by analyzing the current agent process session \
            context and distilling useful memories. This action produces a summary of \
            the memory management operations performed. Maximum 3 new memories per execution. \
            No duplicates. Evict oldest if capacity exceeded.""")
    public MemoryLearningResult learnFromProcess(List<AgenticAggregateMemory> memories) {
        int currentCount = (memories != null) ? memories.size() : 0;
        return new MemoryLearningResult(0, 0,
                "Learning process completed. Current memory count: " + currentCount);
    }

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    /**
     * Checks whether a memory entry matches a lowercase search query.
     *
     * <p>The match is case-insensitive and checks the memory's {@code subject},
     * {@code fact}, and {@code reason} fields.
     *
     * @param memory     the memory entry to check
     * @param lowerQuery the search query in lowercase
     * @return {@code true} if any of the checked fields contain the query
     */
    private static boolean matchesQuery(AgenticAggregateMemory memory, String lowerQuery) {
        return containsIgnoreCase(memory.subject(), lowerQuery)
                || containsIgnoreCase(memory.fact(), lowerQuery)
                || containsIgnoreCase(memory.reason(), lowerQuery);
    }

    /**
     * Null-safe, case-insensitive substring check.
     *
     * @param text  the text to search within; may be {@code null}
     * @param lower the lowercase search term
     * @return {@code true} if {@code text} contains {@code lower} (case-insensitive)
     */
    private static boolean containsIgnoreCase(String text, String lower) {
        return text != null && text.toLowerCase().contains(lower);
    }
}
